CREATE TABLE public.regions (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL,
    translations text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL,
    "wikiDataId" character varying(255),

    CONSTRAINT regions_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.regions."wikiDataId" IS 'Rapid API GeoDB Cities';