CREATE TABLE public.subregions (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL,
    translations text,
    region_id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL,
    "wikiDataId" character varying(255),

    CONSTRAINT subregions_pkey PRIMARY KEY (id),
    CONSTRAINT subregions_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id)
);

CREATE INDEX subregions_region_id_idx ON public.subregions USING btree (region_id);

COMMENT ON COLUMN public.subregions."wikiDataId" IS 'Rapid API GeoDB Cities';