CREATE TABLE public.countries (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL,
    iso3 character(3),
    numeric_code character(3),
    iso2 character(2),
    phonecode character varying(255),
    capital character varying(255),
    currency character varying(255),
    currency_name character varying(255),
    currency_symbol character varying(255),
    tld character varying(255),
    native character varying(255),
    population bigint,
    gdp bigint,
    region character varying(255),
    region_id bigint,
    subregion character varying(255),
    subregion_id bigint,
    nationality character varying(255),
    area_sq_km double precision,
    postal_code_format character varying(255),
    postal_code_regex character varying(255),
    timezones text,
    translations text,
    latitude numeric(10,8),
    longitude numeric(11,8),
    emoji character varying(191),
    "emojiU" character varying(191),
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL,
    "wikiDataId" character varying(255),

    CONSTRAINT countries_pkey PRIMARY KEY (id),
    CONSTRAINT countries_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id),
    CONSTRAINT countries_subregion_id_fkey FOREIGN KEY (subregion_id) REFERENCES public.subregions(id)
);

CREATE INDEX countries_region_id_idx ON public.countries USING btree (region_id);
CREATE INDEX countries_subregion_id_idx ON public.countries USING btree (subregion_id);

COMMENT ON COLUMN public.countries."wikiDataId" IS 'Rapid API GeoDB Cities';